sudo: required
language: python
python:
  - "3.5"
dist: trusty
env:
  global:
    - GETH_BASE_INSTALL_PATH=$TRAVIS_BUILD_DIR
  matrix:
    - TOX_ENV=py27-core-stdlib
    - TOX_ENV=py34-core-stdlib
    - TOX_ENV=py35-core-stdlib
    - TOX_ENV=py27-core-gevent
    - TOX_ENV=py34-core-gevent
    - TOX_ENV=py35-core-gevent
    - TOX_ENV=py35-integration-ethtestrpc
    - TOX_ENV=py35-integration-goethereum GETH_VERSION=v1.6.6
    - TOX_ENV=flake8
cache:
  pip: true
before_install:
  - if [ -n "$GETH_VERSION" ]; then travis_retry sudo add-apt-repository -y ppa:gophers/archive; fi
  - if [ -n "$GETH_VERSION" ]; then travis_retry sudo apt-get update; fi
  - if [ -n "$GETH_VERSION" ]; then mkdir -p $HOME/.ethash; fi
install:
  - if [ -n "$GETH_VERSION" ]; then travis_retry sudo apt-get install -y golang-1.7 build-essential; fi
  - travis_retry pip install pip setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - if [ -n "$GETH_VERSION" ]; then travis_retry pip3 install py-geth==1.10.0; fi
  - if [ -n "$GETH_VERSION" ]; then python3 -m geth.install $GETH_VERSION; fi
  - if [ -n "$GETH_VERSION" ]; then export GOROOT=/usr/lib/go-1.7; fi
  - if [ -n "$GETH_VERSION" ]; then export GETH_BINARY="$GETH_BASE_INSTALL_PATH/geth-$GETH_VERSION/bin/geth"; fi
  - if [ -n "$GETH_VERSION" ]; then $GETH_BINARY version; fi
  - if [ -n "$GETH_VERSION" ]; then $GETH_BINARY makedag 0 $HOME/.ethash; fi
  - pip freeze
script:
  - tox -e $TOX_ENV --recreate
after_script:
  - cat .tox/$TOX_ENV/log/*.log
