sudo: required
language: python
python:
  - "3.5"
dist: trusty
env:
  global:
    - GETH_BASE_INSTALL_PATH=$TRAVIS_BUILD_DIR
  matrix:
    - TOX_POSARGS="-e py27-core-stdlib"
    - TOX_POSARGS="-e py34-core-stdlib"
    - TOX_POSARGS="-e py35-core-stdlib"
    - TOX_POSARGS="-e py27-core-gevent"
    - TOX_POSARGS="-e py34-core-gevent"
    - TOX_POSARGS="-e py35-core-gevent"
    # eth-testrpc
    - TOX_POSARGS="-e py27-integration-ethtestrpc -e py34-integration-ethtestrpc -e py35-integration-ethtestrpc"
    # ethereum-tester
    - TOX_POSARGS="-e py27-integration-ethtester -e py34-integration-ethtester -e py35-integration-ethtester"
    # go-ethereum
    - TOX_POSARGS="-e py27-integration-goethereum -e py34-integration-goethereum -e py35-integration-goethereum" GETH_VERSION=v1.6.0
    - TOX_POSARGS="-e py27-integration-goethereum -e py34-integration-goethereum -e py35-integration-goethereum" GETH_VERSION=v1.6.1
    - TOX_POSARGS="-e py27-integration-goethereum -e py34-integration-goethereum -e py35-integration-goethereum" GETH_VERSION=v1.6.4
    - TOX_POSARGS="-e py27-integration-goethereum -e py34-integration-goethereum -e py35-integration-goethereum" GETH_VERSION=v1.6.5
    - TOX_POSARGS="-e py27-integration-goethereum -e py34-integration-goethereum -e py35-integration-goethereum" GETH_VERSION=v1.6.6
    - TOX_POSARGS="-e py27-integration-goethereum -e py34-integration-goethereum -e py35-integration-goethereum" GETH_VERSION=v1.6.7
    - TOX_POSARGS="-e flake8"
cache:
  - pip: true
  - directories:
    - $HOME/.ethash/
before_install:
  - if [ -n "$GETH_VERSION" ]; then travis_retry sudo add-apt-repository -y ppa:gophers/archive; fi
  - if [ -n "$GETH_VERSION" ]; then travis_retry sudo apt-get update; fi
  - if [ -n "$GETH_VERSION" ]; then mkdir -p $HOME/.ethash; fi
install:
  - if [ -n "$GETH_VERSION" ]; then travis_retry sudo apt-get install -y golang-1.7 build-essential; fi
  - travis_retry pip install pip setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - if [ -n "$GETH_VERSION" ]; then travis_retry pip3 install py-geth==1.10.0; fi
  - if [ -n "$GETH_VERSION" ]; then python3 -m geth.install $GETH_VERSION; fi
  - if [ -n "$GETH_VERSION" ]; then export GOROOT=/usr/lib/go-1.7; fi
  - if [ -n "$GETH_VERSION" ]; then export GETH_BINARY="$GETH_BASE_INSTALL_PATH/geth-$GETH_VERSION/bin/geth"; fi
  - if [ -n "$GETH_VERSION" ]; then $GETH_BINARY version; fi
  - if [ -n "$GETH_VERSION" ]; then $GETH_BINARY makedag 0 $HOME/.ethash; fi
  - pip freeze
script:
  - tox $TOX_POSARGS
